sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
    - php: 7
    - php: 7
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
    - php: hhvm
    - php: hhvm
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"

before_install:
  - composer self-update
  - if [[ $ZEND_SERVICEMANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$ZEND_SERVICEMANAGER_VERSION" ; fi
  - if [[ $ZEND_SERVICEMANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi


install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-dist --no-scripts

script:
  - composer test
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi
